### PR TITLE
Update zh_CN.lang

### PR DESCRIPTION
**Pull request by Mrkwtkr**
I'm back :D

### CODE REVIEW

**Comment by Adaptivity** [comment]
Welcome back :) What about "Sneaky Facades"? It's like hidden facades :D

**Comment by tterrag1098** [comment]
Could you squash possibly? :)

**Comment by tterrag1098** [comment]
https://github.com/CrazyPants/EnderIO/pull/1692#issuecomment-70351606 <- how to

**Comment by tterrag1098** [comment]
Of course in your case `~6` would be `~3` as you only have 3 commits.

**Pull request closed without merging**
