### PR TITLE
Removed unnecessary client sync

### PR DESCRIPTION
**Pull request by HenryLoenwind**
50% FPS drop from just a single buffer is a bit too much...

### CODE REVIEW

**Comment by tterrag1098** [comment]
How exactly was the previous code flawed?

**Comment by HenryLoenwind** [comment]
@MatthiasMann Could you elaborate?

**Comment by MatthiasMann** [comment]
Returning true from processTasks will cause a block update between server and client. But there is already a lower frequency sync of the energy buffer in the base class which works without a block update. So returning false saves on block updates without causing a desync.

**Comment by HenryLoenwind** [comment]
Thanks, MatthiasMann.

I'd like to add that we found this issue because placing a single energy buffer cause me to lose about 50% FPS. It's very repeatable by switching between an energy conduit and a buffer. (MP with server in same LAN on a different PC).

**Pull request merged**
